package reporter

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"time"

	"github.com/yuin/goldmark"
	"github.com/yuin/goldmark/extension"
	"github.com/yuin/goldmark/renderer/html"
)

const htmlTemplate = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
  @page {
    size: A4;
    margin: 2cm 2cm 2.5cm 2cm;
    @bottom-center {
      content: counter(page) " / " counter(pages);
      font-size: 8pt;
      color: #94A3B8;
    }
  }
  body {
    font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
    font-size: 11pt;
    line-height: 1.6;
    color: #0F172A;
    max-width: 100%%;
  }

  /* ── Headings ── */
  h1 {
    color: #0EA5E9;
    border-bottom: 3px solid #0EA5E9;
    padding-bottom: 8px;
    font-size: 20pt;
    margin-top: 28px;
  }
  h2 {
    color: #0F172A;
    border-bottom: 2px solid #BAE6FD;
    padding-bottom: 6px;
    font-size: 15pt;
    margin-top: 24px;
  }
  h3 {
    color: #334155;
    font-size: 13pt;
    margin-top: 18px;
  }

  /* ── Tables ── */
  table {
    width: 100%%;
    border-collapse: collapse;
    margin: 16px 0;
    font-size: 10pt;
    border-radius: 6px;
    overflow: hidden;
  }
  th {
    background: linear-gradient(135deg, #0EA5E9, #38BDF8);
    color: white;
    padding: 10px 12px;
    text-align: left;
    font-weight: 600;
    font-size: 9pt;
    text-transform: uppercase;
    letter-spacing: 0.5px;
  }
  td {
    padding: 9px 12px;
    border-bottom: 1px solid #E2E8F0;
  }
  tr:nth-child(even) {
    background-color: #F0F9FF;
  }

  /* ── Code ── */
  code {
    background-color: #F0F9FF;
    color: #0EA5E9;
    padding: 2px 6px;
    border-radius: 3px;
    font-family: 'Courier New', monospace;
    font-size: 9pt;
    border: 1px solid #BAE6FD;
  }
  pre {
    background-color: #0F172A;
    color: #E2E8F0;
    padding: 14px 18px;
    border-radius: 8px;
    border-left: 4px solid #38BDF8;
    overflow-x: auto;
    font-size: 9pt;
  }
  pre code {
    background: none;
    color: inherit;
    padding: 0;
    border: none;
  }

  /* ── Status indicators ── */
  .pass { color: #34D399; font-weight: bold; }
  .fail { color: #FB7185; font-weight: bold; }

  /* ── Blockquote ── */
  blockquote {
    border-left: 4px solid #38BDF8;
    margin: 16px 0;
    padding: 10px 18px;
    background-color: #F0F9FF;
    color: #334155;
    border-radius: 0 6px 6px 0;
  }

  /* ── Lists ── */
  ul, ol {
    padding-left: 24px;
  }
  li {
    margin-bottom: 4px;
  }

  hr {
    border: none;
    border-top: 2px solid #BAE6FD;
    margin: 28px 0;
  }

  /* ── Footer ── */
  .footer {
    margin-top: 40px;
    padding-top: 14px;
    border-top: 2px solid #BAE6FD;
    font-size: 9pt;
    color: #94A3B8;
    text-align: center;
  }
  .footer strong {
    color: #0EA5E9;
  }
</style>
</head>
<body>
%s
<div class="footer">Generated by <strong>Octrafic</strong> — %s</div>
</body>
</html>`

// CheckWeasyPrint checks if weasyprint is installed and available in PATH.
func CheckWeasyPrint() error {
	_, err := exec.LookPath("weasyprint")
	if err != nil {
		return fmt.Errorf("weasyprint is not installed. Install it with: pip install weasyprint")
	}
	return nil
}

// GeneratePDF converts markdown content to a PDF file.
// It returns the absolute path to the generated PDF file.
func GeneratePDF(markdownContent string, outputPath string) (string, error) {
	if err := CheckWeasyPrint(); err != nil {
		return "", err
	}

	// Convert markdown to HTML using goldmark
	md := goldmark.New(
		goldmark.WithExtensions(extension.GFM),
		goldmark.WithRendererOptions(html.WithUnsafe()),
	)

	var htmlBody bytes.Buffer
	if err := md.Convert([]byte(markdownContent), &htmlBody); err != nil {
		return "", fmt.Errorf("failed to convert markdown to HTML: %w", err)
	}

	timestamp := time.Now().Format("2006-01-02 15:04:05")
	fullHTML := fmt.Sprintf(htmlTemplate, htmlBody.String(), timestamp)

	// Always save reports to ~/Documents/octrafic/
	homeDir, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("failed to get home directory: %w", err)
	}
	docsDir := filepath.Join(homeDir, "Documents", "octrafic")
	if err := os.MkdirAll(docsDir, 0o755); err != nil {
		return "", fmt.Errorf("failed to create output directory: %w", err)
	}

	if outputPath == "" {
		outputPath = fmt.Sprintf("octrafic-report-%s.pdf", time.Now().Format("2006-01-02_150405"))
	}
	absPath := filepath.Join(docsDir, filepath.Base(outputPath))

	// Write HTML to temp file
	tmpFile, err := os.CreateTemp("", "octrafic-report-*.html")
	if err != nil {
		return "", fmt.Errorf("failed to create temp file: %w", err)
	}
	defer os.Remove(tmpFile.Name())

	if _, err := tmpFile.WriteString(fullHTML); err != nil {
		tmpFile.Close()
		return "", fmt.Errorf("failed to write HTML: %w", err)
	}
	tmpFile.Close()

	// Convert HTML to PDF using weasyprint
	cmd := exec.Command("weasyprint", tmpFile.Name(), absPath)
	if output, err := cmd.CombinedOutput(); err != nil {
		return "", fmt.Errorf("weasyprint failed: %s — %w", string(output), err)
	}

	return absPath, nil
}
